# Generated by Django 6.0.3 on 2026-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_lifestyle_attendance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='program',
            field=models.CharField(choices=[('UG', 'Bachelors'), ('PG', 'Post Graduate'), ('LLB', 'LLB'), ('MBBS', 'MBBS')], default='UG', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.IntegerField(),
        ),
    ]
